 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tempest                                                     
     # Surfaces =   5
     # Strips   = 162
     # Vortices =1296

  Sref = 0.63160       Cref = 0.20800       Bref =  3.2229    
  Xref = 0.95300E-01   Yref =  0.0000       Zref =-0.38100E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.83235     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =  -0.02003     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.42086     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.42000
  CDtot =   0.03348
  CDvis =   0.03000     CDind =   0.00348
  CLff  =   0.41988     CDff  =   0.00352    | Trefftz
  CYff  =   0.00000         e =    0.9693    | Plane  

   Flap            =   0.00000
   Aileron         =   0.00000
   Elevator        =  -0.63394
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.196683    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.367231
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.080738
 y  mom.  Cm |    Cma =  -1.634010    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.080613

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.137584    CLr =   0.000000
 y  force CY |    CYp =  -0.064992    CYq =   0.000000    CYr =   0.213412
 x' mom.  Cl'|    Clp =  -0.686618    Clq =   0.000000    Clr =   0.119718
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -24.376066    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.039384    Cnq =   0.000000    Cnr =  -0.052324

                  Flap         d1     Aileron      d2     Elevator     d3     Rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.028089   CLd2 =   0.000000   CLd3 =   0.006776   CLd4 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.000754   CYd3 =   0.000000   CYd4 =   0.003056
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =  -0.006290   Cld3 =   0.000000   Cld4 =   0.000157
 y  mom.  Cm |   Cmd1 =   0.003957   Cmd2 =   0.000000   Cmd3 =  -0.028684   Cmd4 =   0.000000
 z' mom.  Cn'|   Cnd1 =   0.000000   Cnd2 =  -0.000078   Cnd3 =   0.000000   Cnd4 =  -0.000856
 Trefftz drag| CDffd1 =   0.000410 CDffd2 =   0.000000 CDffd3 =   0.000059 CDffd4 =   0.000000
 span eff.   |    ed1 =   0.016648    ed2 =   0.000000    ed3 =   0.014857    ed4 =   0.000000



 Neutral point  Xnp =   0.150148

 Clb Cnr / Clr Cnb  =   0.437738    (  > 1 if spirally stable )
